In [2]:
!pip install ucimlrepo

In [3]:
from ucimlrepo import fetch_ucirepo
import pandas as pd

# Fetch the Heart Disease dataset (ID 45 in UCI repository)
heart_disease = fetch_ucirepo(id=45)
X = heart_disease.data.features
y = heart_disease.data.targets

# Display basic information about the dataset
print(heart_disease.metadata)
print(heart_disease.variables)


{'uci_id': 45, 'name': 'Heart Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/45/heart+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/45/data.csv', 'abstract': '4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 303, 'num_features': 13, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['num'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1989, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C52P4X', 'creators': ['Andras Janosi', 'William Steinbrunn', 'Matthias Pfisterer', 'Robert Detrano'], 'intro_paper': {'ID': 231, 'type': 'NATIVE', 'title': 'International application of a new probability algorithm for the diagnosis of coronary artery disease.', 'authors': 'R. Detrano, A. Jánosi, W. Steinbrunn, M

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, classification_report

# Create the Random Forest model
rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Perform 10-fold cross-validation
rf_cv_scores = cross_val_score(rf, X, y, cv=10, scoring='accuracy')

# Confusion Matrix and Classification Report
rf.fit(X, y)
y_pred = rf.predict(X)
cm_rf = confusion_matrix(y, y_pred)
cr_rf = classification_report(y, y_pred)

print(f"Random Forest - Accuracy: {rf_cv_scores.mean()}")
print(f"Confusion Matrix:\n{cm_rf}")
print(f"Classification Report:\n{cr_rf}")


/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example usi

Random Forest - Accuracy: 0.5770967741935483
Confusion Matrix:
[[164   0   0   0   0]
 [  0  55   0   0   0]
 [  0   0  36   0   0]
 [  0   0   0  35   0]
 [  0   0   0   0  13]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       164
           1       1.00      1.00      1.00        55
           2       1.00      1.00      1.00        36
           3       1.00      1.00      1.00        35
           4       1.00      1.00      1.00        13

    accuracy                           1.00       303
   macro avg       1.00      1.00      1.00       303
weighted avg       1.00      1.00      1.00       303



/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Bidirectional, Dense
from tensorflow.keras.preprocessing import sequence
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report

# Preprocess data for LSTM
X_encoded = X.values  # Assuming X is a DataFrame, convert it to NumPy array for compatibility
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

# Build the Bidirectional LSTM model
model = Sequential()
model.add(Bidirectional(LSTM(64, return_sequences=True), input_shape=(X_train.shape[1], 1)))
model.add(Bidirectional(LSTM(64)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Reshape input for LSTM (3D input)
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Evaluate the model
y_pred = (model.predict(X_test) > 0.5).astype(int)
cm_lstm = confusion_matrix(y_test, y_pred)
cr_lstm = classification_report(y_test, y_pred)

print(f"Bi-LSTM - Confusion Matrix:\n{cm_lstm}")
print(f"Classification Report:\n{cr_lstm}")


Epoch 1/10


/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


8/8 ━━━━━━━━━━━━━━━━━━━━ 5s 85ms/step - accuracy: 0.4272 - loss: nan - val_accuracy: 0.4754 - val_loss: nan
Epoch 2/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5259 - loss: nan - val_accuracy: 0.4754 - val_loss: nan
Epoch 3/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5522 - loss: nan - val_accuracy: 0.4754 - val_loss: nan
Epoch 4/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5648 - loss: nan - val_accuracy: 0.4754 - val_loss: nan
Epoch 5/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5725 - loss: nan - val_accuracy: 0.4754 - val_loss: nan
Epoch 6/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5583 - loss: nan - val_accuracy: 0.4754 - val_loss: nan
Epoch 7/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5499 - loss: nan - val_accuracy: 0.4754 - val_loss: nan
Epoch 8/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5706 - loss: nan - val_accuracy: 0.4754 - val_loss: nan
Epoch 9/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [14]:
from sklearn.impute import SimpleImputer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.pipeline import make_pipeline  # Import make_pipeline

# Create the KNN model
knn = KNeighborsClassifier(n_neighbors=5)

# Create an imputer to replace missing values with the mean
imputer = SimpleImputer(strategy='mean')

# Create a pipeline with the imputer and the KNN model
pipeline = make_pipeline(imputer, knn)  # Use make_pipeline

# Perform 10-fold cross-validation using the pipeline
knn_cv_scores = cross_val_score(pipeline, X, y, cv=10, scoring='accuracy')  # Use pipeline

# Confusion Matrix and Classification Report
pipeline.fit(X, y)  # Fit the pipeline
y_pred = pipeline.predict(X)  # Predict using the pipeline
cm_knn = confusion_matrix(y, y_pred)
cr_knn = classification_report(y, y_pred)

print(f"KNN - Accuracy: {knn_cv_scores.mean()}")
print(f"Confusion Matrix:\n{cm_knn}")
print(f"Classification Report:\n{cr_knn}")

KNN - Accuracy: 0.501505376344086
Confusion Matrix:
[[157   4   1   2   0]
 [ 37  17   0   0   1]
 [ 18   9   7   2   0]
 [ 19   7   3   6   0]
 [  5   4   2   0   2]]
Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.96      0.79       164
           1       0.41      0.31      0.35        55
           2       0.54      0.19      0.29        36
           3       0.60      0.17      0.27        35
           4       0.67      0.15      0.25        13

    accuracy                           0.62       303
   macro avg       0.58      0.36      0.39       303
weighted avg       0.60      0.62      0.56       303



/usr/local/lib/python3.11/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.11/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.11/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.11/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for 

In [16]:
import numpy as np
import pandas as pd

# Define function to calculate evaluation metrics
def evaluation_metrics(cm):
    TP = cm[1, 1]
    TN = cm[0, 0]
    FP = cm[0, 1]
    FN = cm[1, 0]

    # Accuracy Formula: (TP + TN) / (TP + TN + FP + FN)
    accuracy = (TP + TN) / (TP + TN + FP + FN)

    # Precision Formula: TP / (TP + FP)
    precision = TP / (TP + FP) if (TP + FP) != 0 else 0

    # Recall Formula: TP / (TP + FN)
    recall = TP / (TP + FN) if (TP + FN) != 0 else 0

    # False Positive Rate (FPR) Formula: FP / (FP + TN)
    FPR = FP / (FP + TN) if (FP + TN) != 0 else 0

    # False Negative Rate (FNR) Formula: FN / (FN + TP)
    FNR = FN / (FN + TP) if (FN + TP) != 0 else 0

    # True Skill Statistic (TSS) Formula: (TP / (TP + FN)) - (FP / (FP + TN))
    TSS = (TP / (TP + FN)) - (FP / (FP + TN))

    # Heidke Skill Score (HSS) Formula: (2 * (TP * TN - FP * FN)) / ((TP + FN) * (FP + TN) + (TP + FP) * (TN + FN))
    HSS = (2 * (TP * TN - FP * FN)) / ((TP + FN) * (FP + TN) + (TP + FP) * (TN + FN))

    return accuracy, precision, recall, FPR, FNR, TSS, HSS

# Assuming confusion matrices for Random Forest, Bi-LSTM, and KNN are already defined (cm_rf, cm_lstm, cm_knn)

# Evaluate for Random Forest
accuracy_rf, precision_rf, recall_rf, FPR_rf, FNR_rf, TSS_rf, HSS_rf = evaluation_metrics(cm_rf)

# Evaluate for Bi-LSTM
accuracy_lstm, precision_lstm, recall_lstm, FPR_lstm, FNR_lstm, TSS_lstm, HSS_lstm = evaluation_metrics(cm_lstm)

# Evaluate for KNN
accuracy_knn, precision_knn, recall_knn, FPR_knn, FNR_knn, TSS_knn, HSS_knn = evaluation_metrics(cm_knn)

# Display evaluation metrics for all models
results = pd.DataFrame({
    'Algorithm': ['Random Forest', 'Bi-LSTM', 'KNN'],
    'Accuracy': [accuracy_rf, accuracy_lstm, accuracy_knn],
    'Precision': [precision_rf, precision_lstm, precision_knn],
    'Recall': [recall_rf, recall_lstm, recall_knn],
    'FPR': [FPR_rf, FPR_lstm, FPR_knn],
    'FNR': [FNR_rf, FNR_lstm, FNR_knn],
    'TSS': [TSS_rf, TSS_lstm, TSS_knn],
    'HSS': [HSS_rf, HSS_lstm, HSS_knn],
})

# Print the results as a table
print(results)


       Algorithm  Accuracy  Precision    Recall       FPR       FNR      TSS  \
0  Random Forest  1.000000   1.000000  1.000000  0.000000  0.000000  1.00000   
1        Bi-LSTM  0.707317   0.000000  0.000000  0.000000  1.000000  0.00000   
2            KNN  0.809302   0.809524  0.314815  0.024845  0.685185  0.28997   

        HSS  
0  1.000000  
1  0.000000  
2  0.394893  
